import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>About</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <div>
          <p className={styles.description}>By coder</p>
          <div className={styles.blog}>
            <h2>Popular Blogs</h2>
            <div className={styles.blogItem}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn JavaScript in 2022?</h3>
              <p>JavaScript is the language used to design logic for the web</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
